---
# tasks file for resume-role
- name: packages update
  apt:
    update_cache: yes
- name: install java
  apt:
    name: openjdk-17-jdk
    state: present
- name: install docker
  apt:
    name: docker.io
    state: present
- name: run docker service
  service:
    name: docker
    state: started
    enabled: yes
- name: python sdk install
  apt:
    name: python3-docker
    state: present
- name: Join swarm as worker
  community.docker.docker_swarm:
    state: join
    join_token: "{{swarm_token}}"
    remote_addrs: ["10.0.2.100"]
    advertise_addr: "10.0.2.50"
